name: sentinelke_field_kit
description: SentinelKE secure field operations app
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  sqflite: ^2.3.3
  path: ^1.9.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
