[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:web]
directory=/app
command=gunicorn sentinelke.asgi:application -c /workspace/deploy/web/gunicorn.conf.py
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
environment=DJANGO_SETTINGS_MODULE="sentinelke.settings"

[program:celery]
directory=/app
command=celery -A sentinelke worker -l info
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
environment=DJANGO_SETTINGS_MODULE="sentinelke.settings"

[program:ussd-service]
directory=/workspace
command=python services/ussd_service/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
