from django.contrib import admin
from django.urls import include, path
from apps.core.views import (
    ai_assistant_view,
    audit_logs_view,
    biometrics_view,
    cases_action_view,
    cases_view,
    cloud_forensics_view,
    compliance_view,
    crypto_tracing_view,
    dashboard_view,
    device_forensics_view,
    dispatch_view,
    drone_feed_view,
    evidence_vault_view,
    field_ops_view,
    financial_crimes_view,
    incidents_view,
    intelligence_view,
    iot_forensics_view,
    mobile_devices_view,
    network_graph_view,
    predictive_ai_view,
    settings_view,
    static_health,
    system_health_view,
    tool_action_view,
    ussd_reports_view,
    warrants_view,
    watchlist_view,
)

handler404 = 'apps.core.views.sentinel_404'
handler500 = 'apps.core.views.sentinel_500'

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('dashboard/', dashboard_view, name='dashboard-home'),
    path('incidents/', incidents_view, name='incidents'),
    path('cases/', cases_view, name='cases'),
    path('cases/actions/<slug:action>/', cases_action_view, name='cases-action'),
    path('dispatch/', dispatch_view, name='dispatch'),
    path('field-ops/', field_ops_view, name='field_ops'),
    path('threat-intelligence/', intelligence_view, name='intelligence'),
    path('watchlist/', watchlist_view, name='watchlist'),
    path('network-graph/', network_graph_view, name='network_graph'),
    path('predictive-ai/', predictive_ai_view, name='predictive_ai'),
    path('ai-assistant/', ai_assistant_view, name='ai_assistant'),
    path('financial-crimes/', financial_crimes_view, name='financial_crimes'),
    path('crypto-tracing/', crypto_tracing_view, name='crypto_tracing'),
    path('biometrics/', biometrics_view, name='biometrics'),
    path('evidence-vault/', evidence_vault_view, name='evidence_vault'),
    path('device-forensics/', device_forensics_view, name='device_forensics'),
    path('cloud-forensics/', cloud_forensics_view, name='cloud_forensics'),
    path('iot-forensics/', iot_forensics_view, name='iot_forensics'),
    path('drone-feed/', drone_feed_view, name='drone_feed'),
    path('mobile-devices/', mobile_devices_view, name='mobile_devices'),
    path('ussd-reports/', ussd_reports_view, name='ussd_reports'),
    path('compliance/', compliance_view, name='compliance'),
    path('warrants/', warrants_view, name='warrants'),
    path('audit-logs/', audit_logs_view, name='audit_logs'),
    path('system-health/', system_health_view, name='system_health'),
    path('settings/', settings_view, name='settings'),
    path('tool-actions/<slug:tool>/<slug:action>/', tool_action_view, name='tool_action'),
    path('system/static-health/', static_health, name='static-health'),
    path('admin/', admin.site.urls),
    path('api/core/', include('apps.core.urls')),
    path('api/audit/', include('apps.audit.urls')),
    path('api/compliance/', include('apps.compliance.urls')),
    path('api/forensics/', include('apps.forensics.urls')),
    path('api/intelligence/', include('apps.intelligence.urls')),
    path('api/fraud/', include('apps.fraud.urls')),
    path('api/surveillance/', include('apps.surveillance.urls')),
    path('api/collaboration/', include('apps.collaboration.urls')),
    path('api/ai-intelligence/', include('apps.ai_intelligence.urls')),
    path('api/operations/', include('apps.operations.urls')),
    path('api/forensics-advanced/', include('apps.forensics_advanced.urls')),
    path('api/biometrics/', include('apps.biometrics.urls')),
    path('api/evidence-automation/', include('apps.evidence_automation.urls')),
    path('api/federation/', include('apps.federation.urls')),
    path('api/ai/', include('apps.ai_gateway.urls')),
]
